# Generated by Django 4.1 on 2024-04-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_movie_actors_alter_movie_genres"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={},
        ),
        migrations.AlterModelManagers(
            name="actor",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="actor",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="password",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="username",
        ),
        migrations.AlterField(
            model_name="actor",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actor",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="cinema.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="cinema.genre"
            ),
        ),
    ]
